version: "3"

services:
  nginx:
    container_name: birdnest-prod-nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - birdnest

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    restart: on-failure
    environment:
      NODE_ENV: production
    networks:
      - birdnest

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    restart: on-failure
    environment:
      NODE_ENV: production
    networks:
      - birdnest

networks:
  birdnest:
